Repository 9oormthon-univ/2024_DANPOONG_TEAM_46_BE, pull requests merged in 2024-11, with the labels that each got.

#3 [feat] 북마크 생성하기 api 구현
  build.gradle
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubController.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/request/BookClubResqeustDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/entity/BookClub.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/entity/ReadType.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/repository/BookClubRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubService.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/ApiResponse.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/ErrorReasonDto.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/exception/GeneralException.java
  src/main/java/com/goormthon/bookduchilseong/global/config/SwaggerConfig.java
Labels: ✨feature

#6 [feat] 북클럽 api 구현
  build.gradle
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookController.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/request/BookRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/request/BookResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/entity/Book.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/entity/ReadStatus.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/repository/BookRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookService.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubController.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/request/BookClubOnlyRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/request/BookClubTogetherRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubDetailDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubGalleryDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubJoinDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubJoinedDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubProgressDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/response/BookClubResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/entity/BookClub.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/repository/BookClubRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubService.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/CertificationRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/CertificationResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/entity/Certification.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/repository/CertificationRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationService.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/controller/MemoController.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/dto/MemoRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/dto/MemoResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/entity/Memo.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/repository/MemoRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/service/MemoService.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/service/MemoServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/entity/User.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/repository/UserRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/userbookclub/entity/UserBookClub.java
  src/main/java/com/goormthon/bookduchilseong/domain/userbookclub/repository/UserBookClubRepository.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/ApiResponse.java
  src/main/java/com/goormthon/bookduchilseong/global/common/BaseEntity.java
Labels: ♻️refactor, ✨feature

#8 [feat] Zodiacsign api 구현
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookController.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubController.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/controller/MemoApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/controller/MemoController.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/entity/User.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignController.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/dto/response/ZodiacsignDetailDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/dto/response/ZodiacsignResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/entity/Zodiacsign.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/entity/Zodiacsigns.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/repository/ZodiacsignRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignService.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignServiceImpl.java
Labels: ✨feature

#11 [feat] 도서 읽기 완료 시 draw 추가
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationService.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/entity/User.java
  src/test/java/com/goormthon/bookduchilseong/domain/certification/CertificationControllerTest.java
Labels: ✨feature

#13 [feat] 에러 핸들러 추가 / 별자리 랜덤 뽑기 구현
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookController.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/request/BookRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/request/BookRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/response/BookResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/entity/Book.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookService.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubController.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/request/BookClubOnlyRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/dto/request/BookClubTogetherRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/entity/BookClub.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/CertificationRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/CertificationResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/request/CertificationRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/dto/response/CertificationResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/entity/Certification.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationService.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/controller/MemoApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/controller/MemoController.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/dto/MemoResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/dto/request/MemoRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/dto/response/MemoResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/entity/Memo.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/service/MemoService.java
  src/main/java/com/goormthon/bookduchilseong/domain/memo/service/MemoServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/entity/User.java
  src/main/java/com/goormthon/bookduchilseong/domain/userbookclub/entity/UserBookClub.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignController.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/entity/Zodiacsign.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/repository/ZodiacsignRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignService.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/status/ErrorStatus.java
  src/test/java/com/goormthon/bookduchilseong/domain/book/BookControllerTest.java
  src/test/java/com/goormthon/bookduchilseong/domain/certification/CertificationControllerTest.java
  src/test/java/com/goormthon/bookduchilseong/domain/memo/MemoControllerTest.java
Labels: ✨feature

#15 [fix] @EnableJpaAuditing 추가
  src/main/java/com/goormthon/bookduchilseong/BookduchilseongApplication.java
Labels: 🐞fix

#16 [feat] 북클럽 생성하기 api 구현, 카카오 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/goormthon/bookduchilseong/domain/book/repository/BookRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/controller/UserController.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/dto/response/UserMyPageReseponseDto.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/entity/User.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/repository/UserRepository.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/service/UserService.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/service/UserServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/repository/ZodiacsignRepository.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/controller/AuthController.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/dto/request/TokenRefreshRequestDto.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/dto/response/AccountLoginResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/dto/response/KakaoUserResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/dto/response/TokenRefreshResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/repository/AuthRepository.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/repository/AuthRepositoryImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/service/AuthService.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/service/AuthServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/service/KakaoService.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/service/KakaoServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/config/RedisConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/config/RestTemplateConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/config/SecurityConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/config/WebClientConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/controller/OAuthController.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/dto/response/KakaoLoginResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/dto/response/KakaoLoginUrlResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/service/OAuthService.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/service/OAuthServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/security/CustomUserDetails.java
  src/main/java/com/goormthon/bookduchilseong/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/goormthon/bookduchilseong/global/security/jwt/JwtTokenProvider.java
  src/test/java/com/goormthon/bookduchilseong/global/auth/AuthRepositoryImplTest.java
Labels: ✨feature

#20 [feat] 인증하기 요약 구현
  build.gradle
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/entity/Certification.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationService.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/service/CertificationServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/gemini/controller/GeminiController.java
  src/main/java/com/goormthon/bookduchilseong/domain/gemini/dto/request/ChatRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/gemini/dto/response/ChatResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/gemini/service/GeminiService.java
  src/main/java/com/goormthon/bookduchilseong/domain/ocr/controller/OCRController.java
  src/main/java/com/goormthon/bookduchilseong/domain/ocr/service/OCRService.java
  src/main/java/com/goormthon/bookduchilseong/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/goormthon/bookduchilseong/global/config/GeminiRestTemplateConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/config/RestTemplateConfig.java
  src/main/java/com/goormthon/bookduchilseong/global/config/SwaggerConfig.java
Labels: ✨feature

#22 [fix] userId 토큰으로 추출하는 로직으로 fix
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/controller/BookController.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/dto/request/BookRequestDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookService.java
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/controller/BookClubController.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubService.java
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/certification/controller/CertificationController.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/controller/UserController.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignApi.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/controller/ZodiacsignController.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignService.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/service/ZodiacsignServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/security/jwt/JwtTokenProvider.java
  src/test/java/com/goormthon/bookduchilseong/global/auth/JwtTokenProviderTest.java
Labels: ♻️refactor

#23 [fix] 토큰관련 공백 제거
  src/main/java/com/goormthon/bookduchilseong/domain/book/service/BookServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/security/jwt/JwtTokenProvider.java
Labels: 🐞fix

#25 [FEAT] 신규가입자 별자리 추가, 정적 파일 추가
  src/main/java/com/goormthon/bookduchilseong/domain/bookclub/service/BookClubService.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/service/UserServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/domain/zodiacsign/entity/Zodiacsigns.java
  src/main/java/com/goormthon/bookduchilseong/global/auth/service/AuthServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/service/OAuthServiceImpl.java
  src/main/resources/templates/zodiacsigns/AQUARIUS.png
  src/main/resources/templates/zodiacsigns/ARIES.png
  src/main/resources/templates/zodiacsigns/CANCER.png
  src/main/resources/templates/zodiacsigns/CAPRICORN.png
  src/main/resources/templates/zodiacsigns/GEMINI.png
  src/main/resources/templates/zodiacsigns/LEO.png
  src/main/resources/templates/zodiacsigns/LIBRA.png
  src/main/resources/templates/zodiacsigns/PISCES.png
  src/main/resources/templates/zodiacsigns/SAGITTARIUS.png
  src/main/resources/templates/zodiacsigns/SCORPIO.png
  src/main/resources/templates/zodiacsigns/TAURUS.png
  src/main/resources/templates/zodiacsigns/VIRGO.png
Labels: ✨feature

#26 [feat] 내 뽑기 조회 / 카카오 로그인 리다이렉트 수정
  src/main/java/com/goormthon/bookduchilseong/domain/user/controller/UserController.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/dto/response/UserDrawResponseDTO.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/service/UserService.java
  src/main/java/com/goormthon/bookduchilseong/domain/user/service/UserServiceImpl.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/controller/OAuthController.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/dto/response/KakaoLoginResponseDto.java
  src/main/java/com/goormthon/bookduchilseong/global/oauth/service/OAuthServiceImpl.java
Labels: ♻️refactor, ✨feature
